In [7]:
from sklearn.feature_selection import mutual_info_classif, f_classif
import pandas as pd

In [4]:
X = pd.read_parquet("X_train.parquet")
y = pd.read_parquet("y_train.parquet")["value"]

X = X.iloc[:, :768]
X = (X != 0).astype(int)

In [16]:
X.sum(axis=0).sort_values().head(50)

0        0
1        0
2        0
3        0
4        0
58       0
57       0
56       0
60       0
61       0
62       0
63       0
59       0
7        0
6        0
5        0
386      0
387      0
388      0
389      0
390      0
391      0
385      0
384      0
440      0
441      0
447      0
446      0
445      0
444      0
443      0
442      0
376    136
383    149
711    166
707    174
704    180
378    191
454    195
449    196
709    206
379    210
710    212
708    213
380    214
381    216
126    221
121    230
706    231
705    234
dtype: int64

In [8]:
# 1a) ANOVA F-score (treating –1,0,1 as three classes)
F, p = f_classif(X, y)
uni = pd.DataFrame({
    'feature': X.columns,
    'F_score': F,
    'p_value': p
}).sort_values('F_score', ascending=False)

# 1b) Mutual information
mi = mutual_info_classif(X, y, discrete_features=True)
uni['MI'] = mi
uni = uni.sort_values('MI', ascending=False)

# Peek at the top 20
print(uni.head(20))

c:\Users\forbe\.local\share\mamba\envs\chess\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:112: UserWarning: Features [  0   1   2   3   4   5   6   7  56  57  58  59  60  61  62  63 384 385
 386 387 388 389 390 391 440 441 442 443 444 445 446 447] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx, UserWarning)
c:\Users\forbe\.local\share\mamba\envs\chess\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:113: RuntimeWarning: invalid value encountered in divide
  f = msb / msw

    feature      F_score       p_value        MI
393     393   127.157624  6.069693e-56  0.004572
89       89    11.232709  1.323583e-05  0.004405
439     439  3050.680111  0.000000e+00  0.003757
432     432  3270.512242  0.000000e+00  0.003756
764     764  2219.489006  0.000000e+00  0.003728
699     699  2141.534794  0.000000e+00  0.003350
675     675    43.427814  1.381526e-19  0.003308
199     199  2412.768112  0.000000e+00  0.003257
251     251    45.303391  2.117770e-20  0.003225
704     704    43.182711  1.765212e-19  0.002973
112     112    10.925800  1.799025e-05  0.002965
601     601    44.713754  3.818843e-20  0.002842
316     316   122.690217  5.282656e-54  0.002574
494     494    43.329069  1.524894e-19  0.002417
444     444          NaN           NaN  0.002375
78       78     4.938497  7.165538e-03  0.002291
719     719    95.198806  4.566875e-42  0.002193
87       87    76.409192  6.583316e-34  0.002041
433     433  2817.486982  0.000000e+00  0.001984
177     177    20.039820  1.981486e-09  0.001980

In [11]:
uni.sort_values("F_score").dropna()

    feature      F_score   p_value        MI
562     562     0.584556  0.557353  0.000092
622     622     0.871231  0.418436  0.000182
93       93     1.060920  0.346138  0.000238
565     565     1.115437  0.327773  0.000157
129     129     1.459125  0.232440  0.000151
..      ...          ...       ...       ...
9         9  3783.841705  0.000000  0.000000
14       14  3812.762224  0.000000  0.000000
8         8  3851.586802  0.000000  0.000000
632     632  4437.930204  0.000000  0.000000
192     192  4594.923803  0.000000  0.000000

[736 rows x 4 columns]